FROM gliderlabs/alpine:edge
RUN echo http://alpine.gliderlabs.com/alpine/edge/testing | tee -a /etc/apk/repositories \
    && echo http://alpine.gliderlabs.com/alpine/edge/community | tee -a /etc/apk/repositories
